apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: shell
      image: arunvelsriram/utils@sha256:406847435268627f67161d387b61c01d5aafe9771e11214639dec2780cab2084
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /cache
          name: cache
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "ps aux | grep -q '[s]leep'"
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "ps aux | grep -q '[s]leep'"
        initialDelaySeconds: 5
        periodSeconds: 10
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
  restartPolicy: Always
  volumes:
    - name: cache
      emptyDir: {}