format = """\
[\uE0C2 ](fg:#7DF9AA)\
$time\
[\uE0CA ](bg:#7DF9AA fg:#3B76F0)\
$directory\
[\uE0C8](fg:#3B76F0 bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[\uE0C0](fg:#FCF392)\
\n\
$cmd_duration\
$character\
"""

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "[](fg:#1C3A5E)[ \uf11e $duration ]($style)[](fg:#1C3A5E)"
style = "fg:bright-white bg:#1C3A5E"

[directory]
format = "[  $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
format = '[  $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[\[$all_status$ahead_behind\] ]($style)'
style = "fg:green bg:#FCF392"

[git_metrics]
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:#FCF392"
disabled = false

[character]
success_symbol = '[ 󱗆](green) '
error_symbol = '[ 󰞇](#E84D44) '

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
format = '[󱑍 $time ](bg:#7DF9AA fg:#1C3A5E)'
